version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reserve_meetingroom
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: ./backend
    image: reserve-meetingroom-api
    environment:
      PORT: 8080
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: reserve_meetingroom
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: ["node","src/server.js"]
volumes:
  pgdata:
